"""empty message

Revision ID: a2d7cf75665b
Revises: 11b3dabbd185
Create Date: 2025-05-04 14:42:35.756477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2d7cf75665b'
down_revision: Union[str, None] = '11b3dabbd185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('location_country_code', sa.String(), nullable=False),
    sa.Column('location_address', sa.String(), nullable=False),
    sa.Column('rating_average', sa.Float(), nullable=False),
    sa.Column('rating_num_votes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotel_review',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('hotel_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotel_room',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hotel_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price_per_night_currency_code', sa.String(), nullable=False),
    sa.Column('price_per_night', sa.Float(), nullable=False),
    sa.Column('numbers', sa.ARRAY(sa.Integer()), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotel_room')
    op.drop_table('hotel_review')
    op.drop_table('hotel')
    # ### end Alembic commands ###
